micronaut:
    application:
        name: issue271
    server:
        port: 8080

datasources:
    default:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: secret
        driverClassName: com.mysql.jdbc.Driver
